### ISSUE TITLE
End Ruins | End

### ISSUE THREAD

**Issue by DeathShadez** [dfsek-org/BetterEnd-Public#34]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Small ruins that spawn randomly throughout the end. The Aether already has ruins of their own, so possibly the end could have some too. They sorta go with shulker nests as well. There could possibly be maybe even bigger types of ruins that spawn.

**Describe alternatives you've considered**
Adapt or change this idea to however you seek fit.

**Additional context**
### Design Concepts
![2020-06-21_22 42 58](https://user-images.githubusercontent.com/51402617/85243833-e43e8380-b410-11ea-8204-9cb7e09f09c6.png)
![2020-06-21_22 43 55](https://user-images.githubusercontent.com/51402617/85243841-ea346480-b410-11ea-8aa6-f1c93b351060.png)
![2020-06-21_22 44 34](https://user-images.githubusercontent.com/51402617/85243853-eef91880-b410-11ea-9db0-7d1aee21a0fc.png)

**Comment by dfsek** [comment]
We actually were going to do this a while ago - no idea what happened to it, but I still think it'd be a good idea.

**Comment by GucciPoochie** [comment]
![2020-07-06_07 44 15 copy](https://user-images.githubusercontent.com/58349185/86606393-c7e82e00-bf5c-11ea-9a2e-0d4ef7d376ad.jpg)
This should be good for now.

**Comment by DeathShadez** [comment]
wow.

**Comment by GucciPoochie** [comment]
easily over 100 in less than an hour's work.

**Comment by dfsek** [comment]
Added in 3.6.4
