### ISSUE TITLE
An unexpected exception was thrown whilst populating item "enchanted_golden_apple"

### ISSUE THREAD

**Issue by TheMrEngMan** [dfsek-org/BetterEnd-Public#64]
**Describe the bug**
Pregenerating the end sometimes causes the following to the thrown in cosole: 
`[Server thread/ERROR]: [BetterEnd] An unexpected exception was thrown whilst populating item "enchanted_golden_apple"`
`[Server thread/WARN]: java.lang.IllegalArgumentException: bound must be positive`

**To Reproduce**
1. Pregenerate the world where BetterEnd is used as the generator with Chunky
2. Wait for an enchanted golden apple to be generated as loot

**Expected behavior**
The error does not occur

**Versions**
***Paper***
This server is running Paper version git-Paper-130 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Previous version: git-Paper-123 (MC: 1.16.1)
You are running the latest version
***BetterEnd***
[BetterEnd] This server is running BetterEnd v3.6.3

**Additional context**
Custom loot tables are not in use
All BetterEnd and Chunky configurations are defaults
The world is being pregenerated from an unexplored state (brand new)
The enchanted golden apple is still created in the chest
[BetterEnd_gereration_error.txt](https://github.com/dfsek-org/BetterEnd-Public/files/5009122/BetterEnd_gereration_error.txt)

**Comment by dfsek** [comment]
#53
