### ISSUE TITLE
Generator stops working on world after reload/restart

### ISSUE THREAD

**Issue by steelwolf97** [dfsek-org/BetterEnd-Public#65]
I have tried to make a BE world using the default end. After every restart the world no longer becomes a BE world and chunk loading issues ensue until the default end is back in place. I use multiverse for the creation and management of my worlds.

**To Reproduce**
1. create a BE world using the multiverse generator command (after deleting the original end)
2. Enter the world and explore(everything works fine)
3. restart server
4. Re-enter the world to find that the generator stopped working for that world including the BE settings for those biomes that did generate beforehand

**Expected behavior**
The generator to consistently stay active.
![2020-08-01_11 53 47](https://user-images.githubusercontent.com/32615392/89105341-3c907a00-d3ee-11ea-8fd2-41e5c8763d92.png)
![2020-08-01_11 53 56](https://user-images.githubusercontent.com/32615392/89105342-3d291080-d3ee-11ea-8b08-fe401bc9c1d8.png)

**Versions**
Please submit the output of the following commands:
`paper version 130
`be version 3.64 premium
**Do not submit just the version number, submit the entire command output!**

**Additional context**

**Comment by dfsek** [comment]
This was caused by not configuring the world in bukkit.yml, I presume?

**Comment by steelwolf97** [comment]
Yes. Originally I never had to use that setting. For some reason that
changed for me.
